import red from '../../lib/red.js';
import { getUsers } from '../../data/users.js';
import { Buffer } from 'buffer';

red.bot({
  cmd: 'gc',
  desc: 'Show detailed group info with members, admins, creator, invite, and more',
  fromMe: false,
  type: 'group',
  react: '📝',
  filename: import.meta.url,
  handler: async (sock, msg, args, { isGroup }) => {
    if (!isGroup) {
      return await sock.sendMessage(msg.key.remoteJid, { text: '❌ This command only works in groups!' }, { quoted: msg });
    }

    const gcId = msg.key.remoteJid;

    // Fetch group metadata
    let groupMetadata;
    try {
      groupMetadata = await sock.groupMetadata(gcId);
    } catch {
      return await sock.sendMessage(gcId, { text: '❌ Failed to fetch group info!' }, { quoted: msg });
    }

    const gcName = groupMetadata.subject;
    const members = groupMetadata.participants.length;

    // Build list of admins and creator
    const adminParticipants = groupMetadata.participants.filter(p => p.admin || p.superAdmin);
    const admins = adminParticipants.map(p => `@${p.id.split('@')[0]}`).join(', ') || 'None';
    const creatorObj = groupMetadata.participants.find(p => p.admin && !p.superAdmin);
    const creator = creatorObj ? `@${creatorObj.id.split('@')[0]}` : 'Unknown';

    const botAdmin = groupMetadata.participants.some(p => p.id === sock.user.id && (p.admin || p.superAdmin)) ? '✅ Yes' : '❌ No';

    // Registered users count from users.js
    const allUsers = getUsers();
    const regsInGroup = groupMetadata.participants.filter(p => allUsers[p.id]).length;

    const gcStatus = groupMetadata.announcement ? '🔒 Closed' : '🔓 Open';
    const createdAt = new Date(groupMetadata.creation * 1000);
    const gcAge = Math.floor((Date.now() - createdAt.getTime()) / (1000 * 60 * 60 * 24));

    // Invite link if bot is admin
    let inviteLink = '❌ Bot is not admin';
    try {
      if (botAdmin === '✅ Yes') {
        const code = await sock.groupInviteCode(gcId);
        inviteLink = `https://chat.whatsapp.com/${code}`;
      }
    } catch {
      inviteLink = '❌ Cannot fetch invite';
    }

    // Group profile picture
    let ppUrl;
    try {
      ppUrl = await sock.profilePictureUrl(gcId, 'image');
    } catch {
      ppUrl = null;
    }

    const text = `
✨🌙─── *GROUP INFO* ───🌙✨

*• Name:* ${gcName}
*• Status:* ${gcStatus}
*• Members:* ${members}
*• Admins:* ${admins}
*• Bot Admin:* ${botAdmin}
*• Age:* ${gcAge} days
*• Creator:* ${creator}
*• Registered Users:* ${regsInGroup}
*• ID:* ${gcId}
*• Invite Link:*
${inviteLink}

────────────────────────
💫 Info Generated by RED
`;

    // Prepare mentions
    const mentions = [];
    if (creatorObj) mentions.push(creatorObj.id);
    adminParticipants.forEach(p => mentions.push(p.id));

    // Send message with profile picture if available
    if (ppUrl) {
      const response = await fetch(ppUrl);
      const arrayBuffer = await response.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      await sock.sendMessage(gcId, { image: buffer, caption: text, mentions }, { quoted: msg });
    } else {
      await sock.sendMessage(gcId, { text, mentions }, { quoted: msg });
    }
  }
});